#Generated by ResourceBundle Editor (http://eclipse-rbe.sourceforge.net)

var after_finish_act = "After completion of the activity";

var after_finish_proc = "Process is completed";

var after_resume_act = "Activity after recovery";

var after_resume_proc = "After recovery process";

var after_start_act = "Activities started";

var after_start_proc = "Process starts";

var after_suspend_act = "Activities suspended after"

var after_suspend_proc = "After the process hangs";

var after_timeout_proc = "After the timeout process"

var appSet = "Application Set";

var asynchronous = "Asynchronous";

var autoExecuteRule = "Logic rules automatically";

var basicInfo = "Basic information: Name of activity can not be empty";

var basicInfo2 = "Basic information: Event name can not contain illegal characters such as'`~!@#$%^&*()'";

var basicInfoExtensionAttr = "Basic information: Extended Properties: Please choose the type URL";

var basicInfoExtensionAttr2 = "Basic Information: Extended attributes: Call URL can not be empty";

var basicType = "Basic type";

var before-start-act = "Activities before the start of";

var before_finish_act = "Activities before the completion of";

var before_finish_proc = "Before the completion of the process";

var before_start_proc = "Before the start of the process";

var boolean = "Boolean";

var canNotExceed100 = "\u4E0D\u80FD\u5927\u4E8E100! \\n";

var constant = "Constant";

var date = "Date";

var email = "E-mail";

var eventAction = "Event Action";

var fieldAtt = "Attribute contains the ,";

var ignore = "Ignore";

var input = "Input";

var java = "Can not exceed the maximum Java integer! \\ N";

var longTextInput = "Long string";

var mustFill = "Must be filled! \\ N";

var mustInteger = "Must be an integer! \\ N";

var mustPositive = "Must be positive! \\ N";

var mutiWorkitemSet = "Set of muti-workitem: Complete the number of";

var mutiWorkitemSet2 = "Set of muti-workitem: Percent Complete";

var numberInput = "No.";

var output = "Output";

var participantInfo = "Participants access to information rules logic";

var reAttr = "Duplicate attribute";

var read = "Read-only";

var read_write = "Read and write";

var reminderTime = "Reminder Time";

var reminderTimeRelevantData = "Reminder time: relevant data: can not be null";

var rollback = "Rollback";

var selectParticipants = "Select Participant";

var setEventAction = "Set event action";

var setProperty = "Set property";

var sltRadio = "Radio button list";

var sltSelect = "Options List";

var startPolicy = "Start Policy Configuration";

var startPolicyRestart = "Start Policy: Restart rules: Please select URL type";

var startPolicyRestart2 = "Start Policy: Restart Rule: Call URL can not be empty";

var synchronous = "Synchronization";

var textInput = "String";

var timeLimit = "Time Limit";

var timeLimitPolicy = "Time limit set policy: time limit";

var timeLimitPolicy2 = "Reminded the time limit set strategy: early";

var timeLimitRelevantData = "Time Limit: relevant data: can not be null";

var user = "User";

var validateLimitedTime = "At least one entry is not empty! \\ N";

var validateLimitedTime1 = "Days must be an integer \\ n";

var validateLimitedTime2 = "Hours must be an integer \\ n";

var validateLimitedTime3 = "Minutes must be an integer \\ n";

var validateLimitedTime4 = "Days value must be between 0 to 3650 \\ n";

var validateLimitedTime5 = "Hours value must be between 0 to 23 \\ n";

var validateLimitedTime6 = "Minutes value must be between 0 and 59 \\ n";

var validateRelativedatPath = "Data path name can not be the same!";

var variable = "Variable";